POST http://localhost:3003/api/users/
Content-Type: application/json

{
  "username": "root",
  "name": "David",
  "password": "root"
}

### Username less than 3 characters
POST http://localhost:3003/api/users/
Content-Type: application/json

{
  "username": "a",
  "name": "David",
  "password": "root"
}